"""
SheetVaidya backend — FastAPI + pandas, Redis-backed sessions (works on
serverless hosts like Vercel, where every request can hit a different,
stateless function instance).

Rule-based/statistical cleanup only — no AI/LLM calls anywhere in this
backend. Cleanup happens via explicit, pre-written pandas "formulas"
(fuzzy dedupe, MAD anomaly detection, missing-value fill, and a small
registry of built-in quick fixes matched by keyword) — nothing is
generated by a model.

Run locally:
    uvicorn app.main:app --reload

Env:
    REDIS_URL          required for session storage (Vercel KV / Upstash /
                        any Redis-protocol store). KV_URL also works.

Endpoints (all under /api — this lets the same Vercel deployment also
serve the static frontend at the site root, see vercel.json):
    GET  /api                        -> friendly landing JSON (see /docs)
    GET  /api/health                 -> liveness check
    POST /api/upload                 -> upload a file, get session_id + preview (rate-limited)
    GET  /api/sheets/{session_id}    -> list sheet names in a multi-sheet Excel upload
    POST /api/switch-sheet           -> switch which sheet is the active working sheet
    GET  /api/preview/{session_id}   -> current working-data preview
    POST /api/reset                  -> undo all fixes, back to original upload
    GET  /api/quick-fixes            -> list of built-in fixes (id + label)
    POST /api/quick-fix              -> describe a problem (or pass fix_id) -> built-in fix applied
    POST /api/smart-duplicates       -> find fuzzy/near-duplicate row groups
    POST /api/apply-dedupe           -> drop chosen duplicate rows
    POST /api/detect-anomalies       -> flag outlier values in a numeric column
    POST /api/drop-rows              -> drop arbitrary row indices (e.g. anomalies)
    POST /api/missing-values         -> per-column missing-value report + suggested fill
    POST /api/fill-missing           -> apply a fill strategy per column
    GET  /api/quality-report/{id}    -> overall data-quality score (0-100) + issue list
    POST /api/undo                   -> step back one change (multi-step, not just reset)
    POST /api/redo                   -> re-apply a change that was undone
    GET  /api/history/{session_id}   -> fix history + can_undo/can_redo flags
    GET  /api/download/{session_id}  -> download as .xlsx / .csv / .pdf (?format=)

    -- Excel-formula-equivalents (app/excel_formulas.py) --
    POST /api/formula/upload-lookup    -> upload a second table for VLOOKUP/HLOOKUP
    POST /api/formula/vlookup          -> VLOOKUP-style merge from the lookup table
    POST /api/formula/index-match      -> same as vlookup (INDEX/MATCH == VLOOKUP for a merge)
    POST /api/formula/hlookup          -> HLOOKUP-style merge (lookup table keyed by row)
    POST /api/formula/pivot            -> pivot table (rows/columns/values/aggfunc)
    POST /api/formula/if                -> IF-style conditional column
    POST /api/formula/aggregate        -> SUM/AVERAGE/COUNT/COUNTIF/SUMIF/... on a column
    POST /api/formula/concatenate      -> CONCATENATE-style column join
    POST /api/formula/text-extract     -> LEFT / RIGHT / MID / LEN
    POST /api/formula/serial-number    -> add a running Sr. No. column
    POST /api/formula/rank             -> RANK-style column
    POST /api/formula/unique           -> UNIQUE-style distinct value list (read-only)

    -- Recipes (app/recipes.py) --
    POST   /api/recipes/save     -> save this session's step log as a named, reusable recipe
    GET    /api/recipes          -> list saved recipe names
    GET    /api/recipes/{name}   -> view a recipe's steps
    DELETE /api/recipes/{name}   -> delete a saved recipe
    POST   /api/recipes/apply    -> replay a saved recipe against the current session's file
"""

from typing import Any, Dict, List, Optional

from fastapi import APIRouter, FastAPI, File, HTTPException, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel

from app import builtin_fixes, excel_formulas, excel_io, ml_tools, quality, recipes, report_pdf, session_store as sessions
from app.logging_config import get_logger

log = get_logger()

app = FastAPI(title="SheetVaidya API")
router = APIRouter(prefix="/api")

# Loosen CORS for local dev / demo. Lock this down to your real frontend
# origin(s) before deploying anywhere public.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    """Safety net: any exception not already an HTTPException (e.g. an
    unexpected bug, or Redis being unreachable somewhere we didn't
    anticipate) still gets a clean JSON response instead of an HTML error
    page — which is exactly what broke the frontend's res.json() calls
    before this was added (see the rate-limit fail-open fix in
    session_store.check_rate_limit for the specific bug that motivated
    this). The frontend can always safely call res.json() on any response.
    """
    log.error("unhandled_exception", extra={"path": str(request.url.path), "error": str(exc)})
    return JSONResponse(status_code=500, content={"detail": f"Server error: {exc}"})


# --------------------------------------------------------------------------- #
# Request/response models
# --------------------------------------------------------------------------- #

class DedupeRequest(BaseModel):
    session_id: str
    columns: Optional[List[str]] = None
    threshold: int = 87


class QuickFixRequest(BaseModel):
    session_id: str
    problem: str = ""            # free-text problem description, matched by keyword
    fix_id: Optional[str] = None  # or skip matching and pick a fix directly (from the chip list)


class ApplyDedupeRequest(BaseModel):
    session_id: str
    drop_indices: List[int]


class AnomalyRequest(BaseModel):
    session_id: str
    column: str
    threshold: float = 3.5


class DropRowsRequest(BaseModel):
    session_id: str
    row_indices: List[int]


class MissingValuesRequest(BaseModel):
    session_id: str


class FillMissingRequest(BaseModel):
    session_id: str
    # {"column_name": {"method": "mean"|"median"|"mode"|"constant"|"ffill"|"bfill"|"drop_rows", "value": <for constant>}}
    strategies: Dict[str, Dict[str, Any]]


class SessionIdRequest(BaseModel):
    session_id: str


class LookupRequest(BaseModel):
    session_id: str
    key_column: str
    lookup_key_column: str
    value_columns: List[str]
    how: str = "left"


class HLookupRequest(BaseModel):
    session_id: str
    key_column: str
    lookup_key_row_index: int
    value_row_index: int


class PivotRequest(BaseModel):
    session_id: str
    index_cols: List[str]
    values_col: str
    agg_func: str = "sum"
    columns_col: Optional[str] = None
    replace_working: bool = False  # if True, pivot result becomes the new working sheet


class IfFormulaRequest(BaseModel):
    session_id: str
    column: str
    op: str
    value: Any
    true_value: Any
    false_value: Any
    new_column: str


class AggregateRequest(BaseModel):
    session_id: str
    column: str
    func: str
    condition_column: Optional[str] = None
    condition_op: Optional[str] = None
    condition_value: Optional[Any] = None


class ConcatenateRequest(BaseModel):
    session_id: str
    columns: List[str]
    separator: str = " "
    new_column: str


class TextExtractRequest(BaseModel):
    session_id: str
    column: str
    mode: str  # left | right | mid | len
    new_column: str
    n: Optional[int] = None
    start: Optional[int] = None
    length: Optional[int] = None


class SerialNumberRequest(BaseModel):
    session_id: str
    new_column: str = "Sr No"
    start: int = 1


class RankRequest(BaseModel):
    session_id: str
    column: str
    new_column: str
    ascending: bool = False


class UniqueRequest(BaseModel):
    session_id: str
    column: str


class SwitchSheetRequest(BaseModel):
    session_id: str
    sheet_name: str


class SaveRecipeRequest(BaseModel):
    session_id: str
    name: str


class ApplyRecipeRequest(BaseModel):
    session_id: str
    name: str


# --------------------------------------------------------------------------- #
# Root / health
# --------------------------------------------------------------------------- #

@router.get("/")
def root():
    return {
        "name": "SheetVaidya API",
        "status": "running",
        "docs": "/docs",
        "health": "/api/health",
        "note": "Ye API /api ke neeche hai. UI ke liye site ka root URL (/) frontend/index.html serve karta hai.",
    }


@router.get("/health")
def health():
    return {"status": "ok"}


# --------------------------------------------------------------------------- #
# Upload / preview / reset
# --------------------------------------------------------------------------- #

@router.post("/upload")
async def upload(request: Request, file: UploadFile = File(...)):
    client_ip = request.client.host if request.client else "unknown"
    if not sessions.check_rate_limit("upload", client_ip, max_requests=20, window_seconds=60):
        log.warning("rate_limit_hit", extra={"bucket": "upload", "client_ip": client_ip})
        raise HTTPException(429, "Bahut zyada uploads ho gaye — thodi der baad try karo (max 20/minute).")

    content = await file.read()
    if not content:
        raise HTTPException(400, "File khali hai.")

    try:
        sheets, active_sheet = excel_io.read_upload_all_sheets(file.filename, content)
    except Exception as e:  # noqa: BLE001
        log.warning("upload_parse_failed", extra={"upload_filename": file.filename, "error": str(e)})
        raise HTTPException(400, f"File padhne mein error: {e}")

    df = sheets[active_sheet]
    if df.empty:
        raise HTTPException(400, "Is file mein koi data nahi mila.")

    try:
        session_id = sessions.create(file.filename, df, sheets=sheets, active_sheet=active_sheet)
    except RuntimeError as e:
        log.error("session_create_failed", extra={"error": str(e)})
        raise HTTPException(500, str(e))

    log.info("upload_success", extra={
        "session_id": session_id, "upload_filename": file.filename,
        "rows": len(df), "sheet_count": len(sheets),
    })
    return {
        "session_id": session_id, "filename": file.filename,
        "available_sheets": list(sheets.keys()), "active_sheet": active_sheet,
        **excel_io.df_preview(df),
    }


@router.get("/sheets/{session_id}")
def get_sheets(session_id: str):
    try:
        return sessions.get_sheet_names(session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")


@router.post("/switch-sheet")
def switch_sheet(payload: SwitchSheetRequest):
    try:
        df = sessions.switch_sheet(payload.session_id, payload.sheet_name)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")
    except sessions.SheetNotFound:
        raise HTTPException(404, f"Sheet '{payload.sheet_name}' nahi mili is file mein.")
    return {"status": "switched", "active_sheet": payload.sheet_name, **excel_io.df_preview(df)}


@router.get("/preview/{session_id}")
def preview(session_id: str, rows: int = 10):
    df = _get_df_or_404(session_id)
    return excel_io.df_preview(df, n=rows)


@router.post("/reset")
def reset(session_id: str):
    try:
        df = sessions.reset(session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")
    return {"status": "reset", **excel_io.df_preview(df)}


# --------------------------------------------------------------------------- #
# Built-in quick fix (describe your problem -> pre-written pandas formula)
# No AI/LLM call — matched by keyword against app/builtin_fixes.REGISTRY.
# --------------------------------------------------------------------------- #

@router.get("/quick-fixes")
def quick_fixes_list():
    return {"fixes": builtin_fixes.list_fixes()}


@router.post("/quick-fix")
def quick_fix(payload: QuickFixRequest):
    df = _get_df_or_404(payload.session_id)

    if payload.fix_id:
        result = builtin_fixes.apply_fix_by_id(df, payload.fix_id)
        if result is None:
            raise HTTPException(400, "Ye fix_id nahi mila. GET /api/quick-fixes se list dekho.")
        matched_label = payload.fix_id
        fix_id = payload.fix_id
    else:
        if not payload.problem.strip():
            raise HTTPException(400, "Problem likho ya ek built-in fix chuno.")
        matched = builtin_fixes.match_fix(payload.problem)
        if not matched:
            available = ", ".join(f["label"] for f in builtin_fixes.list_fixes())
            raise HTTPException(
                404,
                f"Koi built-in fix match nahi hua. Available fixes: {available}",
            )
        result = matched["fn"](df)
        matched_label = matched["label"]
        fix_id = matched["id"]

    new_df, explanation = result
    sessions.update_working_df(
        payload.session_id, new_df,
        instruction=payload.problem or matched_label,
        explanation=explanation,
    )
    sessions.log_recipe_step(payload.session_id, "quick_fix", {"fix_id": fix_id})
    return {"matched_fix": matched_label, "explanation": explanation, **excel_io.df_preview(new_df)}


# --------------------------------------------------------------------------- #
# ML: smart / fuzzy duplicate detection
# --------------------------------------------------------------------------- #

@router.post("/smart-duplicates")
def smart_duplicates(payload: DedupeRequest):
    df = _get_df_or_404(payload.session_id)
    return ml_tools.find_smart_duplicates(df, columns=payload.columns, threshold=payload.threshold)


@router.post("/apply-dedupe")
def apply_dedupe(payload: ApplyDedupeRequest):
    df = _get_df_or_404(payload.session_id)
    new_df = ml_tools.apply_dedupe(df, payload.drop_indices)
    sessions.update_working_df(
        payload.session_id, new_df,
        instruction="[smart-dedupe]",
        explanation=f"{len(payload.drop_indices)} duplicate rows hataye gaye.",
    )
    # Not added to the recipe log — drop_indices are specific to *this*
    # file's rows and wouldn't mean anything replayed against a new file.
    return excel_io.df_preview(new_df)


# --------------------------------------------------------------------------- #
# ML: numeric anomaly detection (median absolute deviation — no heavy deps)
# --------------------------------------------------------------------------- #

@router.post("/detect-anomalies")
def detect_anomalies(payload: AnomalyRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        result = ml_tools.detect_anomalies(df, payload.column, threshold=payload.threshold)
    except ValueError as e:
        raise HTTPException(400, str(e))
    return result


@router.post("/drop-rows")
def drop_rows(payload: DropRowsRequest):
    df = _get_df_or_404(payload.session_id)
    new_df = df.drop(index=payload.row_indices).reset_index(drop=True)
    sessions.update_working_df(
        payload.session_id, new_df,
        instruction="[manual-drop]",
        explanation=f"{len(payload.row_indices)} rows manually hataye gaye.",
    )
    # Not added to the recipe log — same reasoning as apply_dedupe above.
    return excel_io.df_preview(new_df)


# --------------------------------------------------------------------------- #
# Missing-value detection + smart fill
# --------------------------------------------------------------------------- #

@router.post("/missing-values")
def missing_values(payload: MissingValuesRequest):
    df = _get_df_or_404(payload.session_id)
    return ml_tools.missing_value_report(df)


@router.post("/fill-missing")
def fill_missing(payload: FillMissingRequest):
    df = _get_df_or_404(payload.session_id)
    if not payload.strategies:
        raise HTTPException(400, "Koi fill strategy nahi di gayi.")

    new_df = ml_tools.fill_missing(df, payload.strategies)
    cols_filled = ", ".join(payload.strategies.keys())
    sessions.update_working_df(
        payload.session_id, new_df,
        instruction="[fill-missing]",
        explanation=f"Missing values fill kiye: {cols_filled}.",
    )
    sessions.log_recipe_step(payload.session_id, "fill_missing", {"strategies": payload.strategies})
    return excel_io.df_preview(new_df)


# --------------------------------------------------------------------------- #
# Data quality report
# --------------------------------------------------------------------------- #


@router.get("/quality-report/{session_id}")
def quality_report(session_id: str):
    df = _get_df_or_404(session_id)
    return quality.compute_report(df)


# --------------------------------------------------------------------------- #
# Undo / redo / history
# --------------------------------------------------------------------------- #

@router.post("/undo")
def undo(payload: SessionIdRequest):
    try:
        df = sessions.undo(payload.session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")
    except sessions.NoUndoAvailable:
        raise HTTPException(400, "Undo karne ke liye kuch nahi hai.")
    return {"status": "undone", **excel_io.df_preview(df)}


@router.post("/redo")
def redo(payload: SessionIdRequest):
    try:
        df = sessions.redo(payload.session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")
    except sessions.NoRedoAvailable:
        raise HTTPException(400, "Redo karne ke liye kuch nahi hai.")
    return {"status": "redone", **excel_io.df_preview(df)}


@router.get("/history/{session_id}")
def history(session_id: str):
    try:
        return sessions.get_history_status(session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")


# --------------------------------------------------------------------------- #
# Download
# --------------------------------------------------------------------------- #

@router.get("/download/{session_id}")
def download(session_id: str, format: str = "xlsx"):  # noqa: A002 (query param name matches API contract)
    df = _get_df_or_404(session_id)
    fmt = format.lower()
    short_id = session_id[:8]

    if fmt == "csv":
        return Response(
            content=excel_io.df_to_csv_bytes(df),
            media_type="text/csv",
            headers={"Content-Disposition": f"attachment; filename=sheetvaidya-fixed-{short_id}.csv"},
        )

    if fmt == "pdf":
        try:
            filename = sessions.get_filename(session_id)
        except sessions.SessionNotFound:
            filename = "uploaded file"
        report = quality.compute_report(df)
        fix_history = sessions.get_history_status(session_id)["history"]
        pdf_bytes = report_pdf.build_quality_report_pdf(filename, report, fix_history)
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=sheetvaidya-quality-report-{short_id}.pdf"},
        )

    if fmt != "xlsx":
        raise HTTPException(400, "format sirf 'xlsx', 'csv', ya 'pdf' ho sakta hai.")

    return Response(
        content=excel_io.df_to_xlsx_bytes(df),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename=sheetvaidya-fixed-{short_id}.xlsx"},
    )


# --------------------------------------------------------------------------- #
# Excel-formula-equivalents: VLOOKUP / HLOOKUP / INDEX-MATCH / Pivot / IF /
# SUM-family aggregates / CONCATENATE / LEFT-RIGHT-MID / RANK / UNIQUE.
# No AI/LLM — every operation is a plain, pre-written pandas function; the
# frontend's formula forms supply the explicit parameters (columns,
# conditions, aggregation) since these can't be guessed from a keyword.
# --------------------------------------------------------------------------- #

@router.post("/formula/upload-lookup")
async def upload_lookup_table(request: Request, session_id: str, file: UploadFile = File(...)):
    _get_df_or_404(session_id)  # 404s early if the main session doesn't exist
    client_ip = request.client.host if request.client else "unknown"
    if not sessions.check_rate_limit("upload", client_ip, max_requests=20, window_seconds=60):
        raise HTTPException(429, "Bahut zyada uploads ho gaye — thodi der baad try karo (max 20/minute).")

    content = await file.read()
    if not content:
        raise HTTPException(400, "Lookup file khali hai.")
    try:
        lookup_df = excel_io.read_upload(file.filename, content)
    except Exception as e:  # noqa: BLE001
        raise HTTPException(400, f"Lookup file padhne mein error: {e}")
    if lookup_df.empty:
        raise HTTPException(400, "Lookup file mein koi data nahi mila.")

    sessions.set_lookup_df(session_id, lookup_df, filename=file.filename)
    return {"status": "lookup_uploaded", "filename": file.filename, **excel_io.df_preview(lookup_df)}


@router.get("/formula/lookup-preview/{session_id}")
def lookup_preview(session_id: str):
    try:
        lookup_df = sessions.get_lookup_df(session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")
    except sessions.LookupNotFound:
        raise HTTPException(404, "Abhi tak koi lookup table upload nahi hui.")
    return excel_io.df_preview(lookup_df)


def _run_lookup(payload: LookupRequest, action: str):
    df = _get_df_or_404(payload.session_id)
    try:
        lookup_df = sessions.get_lookup_df(payload.session_id)
    except sessions.LookupNotFound:
        raise HTTPException(400, "Pehle POST /api/formula/upload-lookup se lookup table upload karo.")
    try:
        new_df, explanation = excel_formulas.vlookup(
            df, lookup_df, payload.key_column, payload.lookup_key_column, payload.value_columns, payload.how,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    sessions.update_working_df(payload.session_id, new_df, instruction="[lookup]", explanation=explanation)
    sessions.log_recipe_step(payload.session_id, action, {
        "key_column": payload.key_column, "lookup_key_column": payload.lookup_key_column,
        "value_columns": payload.value_columns, "how": payload.how,
    })
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/vlookup")
def formula_vlookup(payload: LookupRequest):
    return _run_lookup(payload, "vlookup")


@router.post("/formula/index-match")
def formula_index_match(payload: LookupRequest):
    # Same underlying merge as VLOOKUP — see excel_formulas.vlookup's docstring
    # for why INDEX/MATCH's "look in either direction" advantage doesn't
    # apply once you're joining dataframes instead of reading an Excel range.
    return _run_lookup(payload, "index_match")


@router.post("/formula/hlookup")
def formula_hlookup(payload: HLookupRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        lookup_df = sessions.get_lookup_df(payload.session_id)
    except sessions.LookupNotFound:
        raise HTTPException(400, "Pehle POST /api/formula/upload-lookup se lookup table upload karo.")
    try:
        new_df, explanation = excel_formulas.hlookup(
            df, lookup_df, payload.key_column, payload.lookup_key_row_index, payload.value_row_index,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    sessions.update_working_df(payload.session_id, new_df, instruction="[hlookup]", explanation=explanation)
    sessions.log_recipe_step(payload.session_id, "hlookup", {
        "key_column": payload.key_column, "lookup_key_row_index": payload.lookup_key_row_index,
        "value_row_index": payload.value_row_index,
    })
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/pivot")
def formula_pivot(payload: PivotRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        pivoted, explanation = excel_formulas.pivot_table(
            df, payload.index_cols, payload.values_col, payload.agg_func, payload.columns_col,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    if payload.replace_working:
        sessions.update_working_df(payload.session_id, pivoted, instruction="[pivot]", explanation=explanation)
        sessions.log_recipe_step(payload.session_id, "pivot", {
            "index_cols": payload.index_cols, "values_col": payload.values_col,
            "agg_func": payload.agg_func, "columns_col": payload.columns_col,
        })
    return {
        "explanation": explanation,
        "applied_to_working": payload.replace_working,
        **excel_io.df_preview(pivoted, n=len(pivoted)),
    }


@router.post("/formula/if")
def formula_if(payload: IfFormulaRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        new_df, explanation = excel_formulas.apply_if(
            df, payload.column, payload.op, payload.value,
            payload.true_value, payload.false_value, payload.new_column,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    sessions.update_working_df(payload.session_id, new_df, instruction="[if]", explanation=explanation)
    sessions.log_recipe_step(payload.session_id, "if", {
        "column": payload.column, "op": payload.op, "value": payload.value,
        "true_value": payload.true_value, "false_value": payload.false_value, "new_column": payload.new_column,
    })
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/aggregate")
def formula_aggregate(payload: AggregateRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        result, explanation = excel_formulas.aggregate(
            df, payload.column, payload.func,
            payload.condition_column, payload.condition_op, payload.condition_value,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    return {"result": result, "explanation": explanation}


@router.post("/formula/concatenate")
def formula_concatenate(payload: ConcatenateRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        new_df, explanation = excel_formulas.concatenate(df, payload.columns, payload.separator, payload.new_column)
    except ValueError as e:
        raise HTTPException(400, str(e))
    sessions.update_working_df(payload.session_id, new_df, instruction="[concatenate]", explanation=explanation)
    sessions.log_recipe_step(payload.session_id, "concatenate", {
        "columns": payload.columns, "separator": payload.separator, "new_column": payload.new_column,
    })
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/text-extract")
def formula_text_extract(payload: TextExtractRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        new_df, explanation = excel_formulas.text_extract(
            df, payload.column, payload.mode, payload.new_column, payload.n, payload.start, payload.length,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    sessions.update_working_df(payload.session_id, new_df, instruction="[text-extract]", explanation=explanation)
    sessions.log_recipe_step(payload.session_id, "text_extract", {
        "column": payload.column, "mode": payload.mode, "new_column": payload.new_column,
        "n": payload.n, "start": payload.start, "length": payload.length,
    })
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/serial-number")
def formula_serial_number(payload: SerialNumberRequest):
    df = _get_df_or_404(payload.session_id)
    new_df, explanation = excel_formulas.add_serial_number(df, payload.new_column, payload.start)
    sessions.update_working_df(payload.session_id, new_df, instruction="[serial-number]", explanation=explanation)
    sessions.log_recipe_step(payload.session_id, "serial_number", {
        "new_column": payload.new_column, "start": payload.start,
    })
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/rank")
def formula_rank(payload: RankRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        new_df, explanation = excel_formulas.rank_column(df, payload.column, payload.new_column, payload.ascending)
    except ValueError as e:
        raise HTTPException(400, str(e))
    sessions.update_working_df(payload.session_id, new_df, instruction="[rank]", explanation=explanation)
    sessions.log_recipe_step(payload.session_id, "rank", {
        "column": payload.column, "new_column": payload.new_column, "ascending": payload.ascending,
    })
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/unique")
def formula_unique(payload: UniqueRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        values, explanation = excel_formulas.unique_values(df, payload.column)
    except ValueError as e:
        raise HTTPException(400, str(e))
    return {"values": values, "explanation": explanation}


# --------------------------------------------------------------------------- #
# Recipes: save the sequence of steps applied to this session, replay it
# later against a different file. Only column-name-based steps are
# replayable (see app/recipes.py docstring for what's excluded and why).
# --------------------------------------------------------------------------- #

@router.post("/recipes/save")
def save_recipe(payload: SaveRecipeRequest):
    try:
        steps = sessions.get_recipe_log(payload.session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")
    try:
        sessions.save_recipe(payload.name, steps)
    except ValueError as e:
        raise HTTPException(400, str(e))
    return {"status": "saved", "name": payload.name, "step_count": len(steps)}


@router.get("/recipes")
def list_recipes():
    names = sessions.list_recipe_names()
    return {"recipes": names}


@router.get("/recipes/{name}")
def get_recipe(name: str):
    try:
        recipe = sessions.get_recipe(name)
    except sessions.RecipeNotFound:
        raise HTTPException(404, f"Recipe '{name}' nahi mili.")
    steps_with_labels = [
        {**step, "label": recipes.ACTION_LABELS.get(step.get("action"), step.get("action"))}
        for step in recipe["steps"]
    ]
    return {"name": recipe["name"], "steps": steps_with_labels, "created_at": recipe["created_at"]}


@router.delete("/recipes/{name}")
def delete_recipe(name: str):
    sessions.delete_recipe(name)
    return {"status": "deleted", "name": name}


@router.post("/recipes/apply")
def apply_recipe(payload: ApplyRecipeRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        recipe = sessions.get_recipe(payload.name)
    except sessions.RecipeNotFound:
        raise HTTPException(404, f"Recipe '{payload.name}' nahi mili.")

    lookup_df = None
    try:
        lookup_df = sessions.get_lookup_df(payload.session_id)
    except sessions.LookupNotFound:
        pass  # fine — recipe just skips any lookup-dependent steps, see apply_recipe()

    new_df, applied, skipped = recipes.apply_recipe(df, recipe["steps"], lookup_df=lookup_df)
    log.info("recipe_applied", extra={
        "session_id": payload.session_id, "recipe_name": payload.name,
        "applied_count": len(applied), "skipped_count": len(skipped),
    })
    if applied:
        summary = f"Recipe '{payload.name}' apply ki — {len(applied)} step(s) chale, {len(skipped)} skip hue."
        sessions.update_working_df(payload.session_id, new_df, instruction=f"[recipe:{payload.name}]", explanation=summary)
    return {"applied": applied, "skipped": skipped, **excel_io.df_preview(new_df)}


# --------------------------------------------------------------------------- #

def _get_df_or_404(session_id: str):
    try:
        return sessions.get_working_df(session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")


app.include_router(router)
