"""
SheetVaidya backend — FastAPI + pandas, Redis-backed sessions (works on
serverless hosts like Vercel, where every request can hit a different,
stateless function instance).

Rule-based/statistical cleanup only — no AI/LLM calls anywhere in this
backend. Cleanup happens via explicit, pre-written pandas "formulas"
(fuzzy dedupe, MAD anomaly detection, missing-value fill, and a small
registry of built-in quick fixes matched by keyword) — nothing is
generated by a model.

Run locally:
    uvicorn app.main:app --reload

Env:
    REDIS_URL          required for session storage (Vercel KV / Upstash /
                        any Redis-protocol store). KV_URL also works.

Endpoints (all under /api — this lets the same Vercel deployment also
serve the static frontend at the site root, see vercel.json):
    GET  /api                        -> friendly landing JSON (see /docs)
    GET  /api/health                 -> liveness check
    POST /api/upload                 -> upload a file, get session_id + preview
    GET  /api/preview/{session_id}   -> current working-data preview
    POST /api/reset                  -> undo all fixes, back to original upload
    GET  /api/quick-fixes            -> list of built-in fixes (id + label)
    POST /api/quick-fix              -> describe a problem (or pass fix_id) -> built-in fix applied
    POST /api/smart-duplicates       -> find fuzzy/near-duplicate row groups
    POST /api/apply-dedupe           -> drop chosen duplicate rows
    POST /api/detect-anomalies       -> flag outlier values in a numeric column
    POST /api/drop-rows              -> drop arbitrary row indices (e.g. anomalies)
    POST /api/missing-values         -> per-column missing-value report + suggested fill
    POST /api/fill-missing           -> apply a fill strategy per column
    GET  /api/quality-report/{id}    -> overall data-quality score (0-100) + issue list
    POST /api/undo                   -> step back one change (multi-step, not just reset)
    POST /api/redo                   -> re-apply a change that was undone
    GET  /api/history/{session_id}   -> fix history + can_undo/can_redo flags
    GET  /api/download/{session_id}  -> download as .xlsx / .csv / .pdf (?format=)

    -- Excel-formula-equivalents (app/excel_formulas.py) --
    POST /api/formula/upload-lookup    -> upload a second table for VLOOKUP/HLOOKUP
    POST /api/formula/vlookup          -> VLOOKUP-style merge from the lookup table
    POST /api/formula/index-match      -> same as vlookup (INDEX/MATCH == VLOOKUP for a merge)
    POST /api/formula/hlookup          -> HLOOKUP-style merge (lookup table keyed by row)
    POST /api/formula/pivot            -> pivot table (rows/columns/values/aggfunc)
    POST /api/formula/if                -> IF-style conditional column
    POST /api/formula/aggregate        -> SUM/AVERAGE/COUNT/COUNTIF/SUMIF/... on a column
    POST /api/formula/concatenate      -> CONCATENATE-style column join
    POST /api/formula/text-extract     -> LEFT / RIGHT / MID / LEN
    POST /api/formula/serial-number    -> add a running Sr. No. column
    POST /api/formula/rank             -> RANK-style column
    POST /api/formula/unique           -> UNIQUE-style distinct value list (read-only)
"""

from typing import Any, Dict, List, Optional

from fastapi import APIRouter, FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from pydantic import BaseModel

from app import builtin_fixes, excel_formulas, excel_io, ml_tools, quality, report_pdf, session_store as sessions

app = FastAPI(title="SheetVaidya API")
router = APIRouter(prefix="/api")

# Loosen CORS for local dev / demo. Lock this down to your real frontend
# origin(s) before deploying anywhere public.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# --------------------------------------------------------------------------- #
# Request/response models
# --------------------------------------------------------------------------- #

class DedupeRequest(BaseModel):
    session_id: str
    columns: Optional[List[str]] = None
    threshold: int = 87


class QuickFixRequest(BaseModel):
    session_id: str
    problem: str = ""            # free-text problem description, matched by keyword
    fix_id: Optional[str] = None  # or skip matching and pick a fix directly (from the chip list)


class ApplyDedupeRequest(BaseModel):
    session_id: str
    drop_indices: List[int]


class AnomalyRequest(BaseModel):
    session_id: str
    column: str
    threshold: float = 3.5


class DropRowsRequest(BaseModel):
    session_id: str
    row_indices: List[int]


class MissingValuesRequest(BaseModel):
    session_id: str


class FillMissingRequest(BaseModel):
    session_id: str
    # {"column_name": {"method": "mean"|"median"|"mode"|"constant"|"ffill"|"bfill"|"drop_rows", "value": <for constant>}}
    strategies: Dict[str, Dict[str, Any]]


class SessionIdRequest(BaseModel):
    session_id: str


class LookupRequest(BaseModel):
    session_id: str
    key_column: str
    lookup_key_column: str
    value_columns: List[str]
    how: str = "left"


class HLookupRequest(BaseModel):
    session_id: str
    key_column: str
    lookup_key_row_index: int
    value_row_index: int


class PivotRequest(BaseModel):
    session_id: str
    index_cols: List[str]
    values_col: str
    agg_func: str = "sum"
    columns_col: Optional[str] = None
    replace_working: bool = False  # if True, pivot result becomes the new working sheet


class IfFormulaRequest(BaseModel):
    session_id: str
    column: str
    op: str
    value: Any
    true_value: Any
    false_value: Any
    new_column: str


class AggregateRequest(BaseModel):
    session_id: str
    column: str
    func: str
    condition_column: Optional[str] = None
    condition_op: Optional[str] = None
    condition_value: Optional[Any] = None


class ConcatenateRequest(BaseModel):
    session_id: str
    columns: List[str]
    separator: str = " "
    new_column: str


class TextExtractRequest(BaseModel):
    session_id: str
    column: str
    mode: str  # left | right | mid | len
    new_column: str
    n: Optional[int] = None
    start: Optional[int] = None
    length: Optional[int] = None


class SerialNumberRequest(BaseModel):
    session_id: str
    new_column: str = "Sr No"
    start: int = 1


class RankRequest(BaseModel):
    session_id: str
    column: str
    new_column: str
    ascending: bool = False


class UniqueRequest(BaseModel):
    session_id: str
    column: str


# --------------------------------------------------------------------------- #
# Root / health
# --------------------------------------------------------------------------- #

@router.get("/")
def root():
    return {
        "name": "SheetVaidya API",
        "status": "running",
        "docs": "/docs",
        "health": "/api/health",
        "note": "Ye API /api ke neeche hai. UI ke liye site ka root URL (/) frontend/index.html serve karta hai.",
    }


@router.get("/health")
def health():
    return {"status": "ok"}


# --------------------------------------------------------------------------- #
# Upload / preview / reset
# --------------------------------------------------------------------------- #

@router.post("/upload")
async def upload(file: UploadFile = File(...)):
    content = await file.read()
    if not content:
        raise HTTPException(400, "File khali hai.")

    try:
        df = excel_io.read_upload(file.filename, content)
    except Exception as e:  # noqa: BLE001
        raise HTTPException(400, f"File padhne mein error: {e}")

    if df.empty:
        raise HTTPException(400, "Is file mein koi data nahi mila.")

    try:
        session_id = sessions.create(file.filename, df)
    except RuntimeError as e:
        raise HTTPException(500, str(e))

    return {"session_id": session_id, "filename": file.filename, **excel_io.df_preview(df)}


@router.get("/preview/{session_id}")
def preview(session_id: str, rows: int = 10):
    df = _get_df_or_404(session_id)
    return excel_io.df_preview(df, n=rows)


@router.post("/reset")
def reset(session_id: str):
    try:
        df = sessions.reset(session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")
    return {"status": "reset", **excel_io.df_preview(df)}


# --------------------------------------------------------------------------- #
# Built-in quick fix (describe your problem -> pre-written pandas formula)
# No AI/LLM call — matched by keyword against app/builtin_fixes.REGISTRY.
# --------------------------------------------------------------------------- #

@router.get("/quick-fixes")
def quick_fixes_list():
    return {"fixes": builtin_fixes.list_fixes()}


@router.post("/quick-fix")
def quick_fix(payload: QuickFixRequest):
    df = _get_df_or_404(payload.session_id)

    if payload.fix_id:
        result = builtin_fixes.apply_fix_by_id(df, payload.fix_id)
        if result is None:
            raise HTTPException(400, "Ye fix_id nahi mila. GET /api/quick-fixes se list dekho.")
        matched_label = payload.fix_id
    else:
        if not payload.problem.strip():
            raise HTTPException(400, "Problem likho ya ek built-in fix chuno.")
        matched = builtin_fixes.match_fix(payload.problem)
        if not matched:
            available = ", ".join(f["label"] for f in builtin_fixes.list_fixes())
            raise HTTPException(
                404,
                f"Koi built-in fix match nahi hua. Available fixes: {available}",
            )
        result = matched["fn"](df)
        matched_label = matched["label"]

    new_df, explanation = result
    sessions.update_working_df(
        payload.session_id, new_df,
        instruction=payload.problem or matched_label,
        explanation=explanation,
    )
    return {"matched_fix": matched_label, "explanation": explanation, **excel_io.df_preview(new_df)}


# --------------------------------------------------------------------------- #
# ML: smart / fuzzy duplicate detection
# --------------------------------------------------------------------------- #

@router.post("/smart-duplicates")
def smart_duplicates(payload: DedupeRequest):
    df = _get_df_or_404(payload.session_id)
    return ml_tools.find_smart_duplicates(df, columns=payload.columns, threshold=payload.threshold)


@router.post("/apply-dedupe")
def apply_dedupe(payload: ApplyDedupeRequest):
    df = _get_df_or_404(payload.session_id)
    new_df = ml_tools.apply_dedupe(df, payload.drop_indices)
    sessions.update_working_df(
        payload.session_id, new_df,
        instruction="[smart-dedupe]",
        explanation=f"{len(payload.drop_indices)} duplicate rows hataye gaye.",
    )
    return excel_io.df_preview(new_df)


# --------------------------------------------------------------------------- #
# ML: numeric anomaly detection (median absolute deviation — no heavy deps)
# --------------------------------------------------------------------------- #

@router.post("/detect-anomalies")
def detect_anomalies(payload: AnomalyRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        result = ml_tools.detect_anomalies(df, payload.column, threshold=payload.threshold)
    except ValueError as e:
        raise HTTPException(400, str(e))
    return result


@router.post("/drop-rows")
def drop_rows(payload: DropRowsRequest):
    df = _get_df_or_404(payload.session_id)
    new_df = df.drop(index=payload.row_indices).reset_index(drop=True)
    sessions.update_working_df(
        payload.session_id, new_df,
        instruction="[manual-drop]",
        explanation=f"{len(payload.row_indices)} rows manually hataye gaye.",
    )
    return excel_io.df_preview(new_df)


# --------------------------------------------------------------------------- #
# Missing-value detection + smart fill
# --------------------------------------------------------------------------- #

@router.post("/missing-values")
def missing_values(payload: MissingValuesRequest):
    df = _get_df_or_404(payload.session_id)
    return ml_tools.missing_value_report(df)


@router.post("/fill-missing")
def fill_missing(payload: FillMissingRequest):
    df = _get_df_or_404(payload.session_id)
    if not payload.strategies:
        raise HTTPException(400, "Koi fill strategy nahi di gayi.")

    new_df = ml_tools.fill_missing(df, payload.strategies)
    cols_filled = ", ".join(payload.strategies.keys())
    sessions.update_working_df(
        payload.session_id, new_df,
        instruction="[fill-missing]",
        explanation=f"Missing values fill kiye: {cols_filled}.",
    )
    return excel_io.df_preview(new_df)


# --------------------------------------------------------------------------- #
# Data quality report
# --------------------------------------------------------------------------- #

@router.get("/quality-report/{session_id}")
def quality_report(session_id: str):
    df = _get_df_or_404(session_id)
    return quality.compute_report(df)


# --------------------------------------------------------------------------- #
# Undo / redo / history
# --------------------------------------------------------------------------- #

@router.post("/undo")
def undo(payload: SessionIdRequest):
    try:
        df = sessions.undo(payload.session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")
    except sessions.NoUndoAvailable:
        raise HTTPException(400, "Undo karne ke liye kuch nahi hai.")
    return {"status": "undone", **excel_io.df_preview(df)}


@router.post("/redo")
def redo(payload: SessionIdRequest):
    try:
        df = sessions.redo(payload.session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")
    except sessions.NoRedoAvailable:
        raise HTTPException(400, "Redo karne ke liye kuch nahi hai.")
    return {"status": "redone", **excel_io.df_preview(df)}


@router.get("/history/{session_id}")
def history(session_id: str):
    try:
        return sessions.get_history_status(session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")


# --------------------------------------------------------------------------- #
# Download
# --------------------------------------------------------------------------- #

@router.get("/download/{session_id}")
def download(session_id: str, format: str = "xlsx"):  # noqa: A002 (query param name matches API contract)
    df = _get_df_or_404(session_id)
    fmt = format.lower()
    short_id = session_id[:8]

    if fmt == "csv":
        return Response(
            content=excel_io.df_to_csv_bytes(df),
            media_type="text/csv",
            headers={"Content-Disposition": f"attachment; filename=sheetvaidya-fixed-{short_id}.csv"},
        )

    if fmt == "pdf":
        try:
            filename = sessions.get_filename(session_id)
        except sessions.SessionNotFound:
            filename = "uploaded file"
        report = quality.compute_report(df)
        fix_history = sessions.get_history_status(session_id)["history"]
        pdf_bytes = report_pdf.build_quality_report_pdf(filename, report, fix_history)
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=sheetvaidya-quality-report-{short_id}.pdf"},
        )

    if fmt != "xlsx":
        raise HTTPException(400, "format sirf 'xlsx', 'csv', ya 'pdf' ho sakta hai.")

    return Response(
        content=excel_io.df_to_xlsx_bytes(df),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename=sheetvaidya-fixed-{short_id}.xlsx"},
    )


# --------------------------------------------------------------------------- #
# Excel-formula-equivalents: VLOOKUP / HLOOKUP / INDEX-MATCH / Pivot / IF /
# SUM-family aggregates / CONCATENATE / LEFT-RIGHT-MID / RANK / UNIQUE.
# No AI/LLM — every operation is a plain, pre-written pandas function; the
# frontend's formula forms supply the explicit parameters (columns,
# conditions, aggregation) since these can't be guessed from a keyword.
# --------------------------------------------------------------------------- #

@router.post("/formula/upload-lookup")
async def upload_lookup_table(session_id: str, file: UploadFile = File(...)):
    _get_df_or_404(session_id)  # 404s early if the main session doesn't exist
    content = await file.read()
    if not content:
        raise HTTPException(400, "Lookup file khali hai.")
    try:
        lookup_df = excel_io.read_upload(file.filename, content)
    except Exception as e:  # noqa: BLE001
        raise HTTPException(400, f"Lookup file padhne mein error: {e}")
    if lookup_df.empty:
        raise HTTPException(400, "Lookup file mein koi data nahi mila.")

    sessions.set_lookup_df(session_id, lookup_df, filename=file.filename)
    return {"status": "lookup_uploaded", "filename": file.filename, **excel_io.df_preview(lookup_df)}


@router.get("/formula/lookup-preview/{session_id}")
def lookup_preview(session_id: str):
    try:
        lookup_df = sessions.get_lookup_df(session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")
    except sessions.LookupNotFound:
        raise HTTPException(404, "Abhi tak koi lookup table upload nahi hui.")
    return excel_io.df_preview(lookup_df)


def _run_lookup(payload: LookupRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        lookup_df = sessions.get_lookup_df(payload.session_id)
    except sessions.LookupNotFound:
        raise HTTPException(400, "Pehle POST /api/formula/upload-lookup se lookup table upload karo.")
    try:
        new_df, explanation = excel_formulas.vlookup(
            df, lookup_df, payload.key_column, payload.lookup_key_column, payload.value_columns, payload.how,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    sessions.update_working_df(payload.session_id, new_df, instruction="[lookup]", explanation=explanation)
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/vlookup")
def formula_vlookup(payload: LookupRequest):
    return _run_lookup(payload)


@router.post("/formula/index-match")
def formula_index_match(payload: LookupRequest):
    # Same underlying merge as VLOOKUP — see excel_formulas.vlookup's docstring
    # for why INDEX/MATCH's "look in either direction" advantage doesn't
    # apply once you're joining dataframes instead of reading an Excel range.
    return _run_lookup(payload)


@router.post("/formula/hlookup")
def formula_hlookup(payload: HLookupRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        lookup_df = sessions.get_lookup_df(payload.session_id)
    except sessions.LookupNotFound:
        raise HTTPException(400, "Pehle POST /api/formula/upload-lookup se lookup table upload karo.")
    try:
        new_df, explanation = excel_formulas.hlookup(
            df, lookup_df, payload.key_column, payload.lookup_key_row_index, payload.value_row_index,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    sessions.update_working_df(payload.session_id, new_df, instruction="[hlookup]", explanation=explanation)
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/pivot")
def formula_pivot(payload: PivotRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        pivoted, explanation = excel_formulas.pivot_table(
            df, payload.index_cols, payload.values_col, payload.agg_func, payload.columns_col,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    if payload.replace_working:
        sessions.update_working_df(payload.session_id, pivoted, instruction="[pivot]", explanation=explanation)
    return {
        "explanation": explanation,
        "applied_to_working": payload.replace_working,
        **excel_io.df_preview(pivoted, n=len(pivoted)),
    }


@router.post("/formula/if")
def formula_if(payload: IfFormulaRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        new_df, explanation = excel_formulas.apply_if(
            df, payload.column, payload.op, payload.value,
            payload.true_value, payload.false_value, payload.new_column,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    sessions.update_working_df(payload.session_id, new_df, instruction="[if]", explanation=explanation)
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/aggregate")
def formula_aggregate(payload: AggregateRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        result, explanation = excel_formulas.aggregate(
            df, payload.column, payload.func,
            payload.condition_column, payload.condition_op, payload.condition_value,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    return {"result": result, "explanation": explanation}


@router.post("/formula/concatenate")
def formula_concatenate(payload: ConcatenateRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        new_df, explanation = excel_formulas.concatenate(df, payload.columns, payload.separator, payload.new_column)
    except ValueError as e:
        raise HTTPException(400, str(e))
    sessions.update_working_df(payload.session_id, new_df, instruction="[concatenate]", explanation=explanation)
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/text-extract")
def formula_text_extract(payload: TextExtractRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        new_df, explanation = excel_formulas.text_extract(
            df, payload.column, payload.mode, payload.new_column, payload.n, payload.start, payload.length,
        )
    except ValueError as e:
        raise HTTPException(400, str(e))
    sessions.update_working_df(payload.session_id, new_df, instruction="[text-extract]", explanation=explanation)
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/serial-number")
def formula_serial_number(payload: SerialNumberRequest):
    df = _get_df_or_404(payload.session_id)
    new_df, explanation = excel_formulas.add_serial_number(df, payload.new_column, payload.start)
    sessions.update_working_df(payload.session_id, new_df, instruction="[serial-number]", explanation=explanation)
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/rank")
def formula_rank(payload: RankRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        new_df, explanation = excel_formulas.rank_column(df, payload.column, payload.new_column, payload.ascending)
    except ValueError as e:
        raise HTTPException(400, str(e))
    sessions.update_working_df(payload.session_id, new_df, instruction="[rank]", explanation=explanation)
    return {"explanation": explanation, **excel_io.df_preview(new_df)}


@router.post("/formula/unique")
def formula_unique(payload: UniqueRequest):
    df = _get_df_or_404(payload.session_id)
    try:
        values, explanation = excel_formulas.unique_values(df, payload.column)
    except ValueError as e:
        raise HTTPException(400, str(e))
    return {"values": values, "explanation": explanation}


# --------------------------------------------------------------------------- #

def _get_df_or_404(session_id: str):
    try:
        return sessions.get_working_df(session_id)
    except sessions.SessionNotFound:
        raise HTTPException(404, "Session nahi mila — file dobara upload karo.")


app.include_router(router)
